[workspace]
resolver = "2"
members = [
    "apps/klauncher",
    "apps/kbar",
    "crates/theme",
    "crates/niri",
    "tools/theme-gen",
]
default-members = [
    "apps/klauncher",
    "apps/kbar",
    "crates/theme",
    "crates/niri",
    "tools/theme-gen",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
gtk4 = { version = "0.11", features = ["v4_12"] }
gtk4-layer-shell = "0.8"
libc = "0.2"
serde_json = "1"
kshell-niri = { path = "crates/niri" }
kshell-theme = { path = "crates/theme" }
