[package]
name = "kbar"
version.workspace = true
edition.workspace = true
description = "A compact GTK4 desktop bar for Wayland and Niri"
license.workspace = true

[dependencies]
futures-channel.workspace = true
futures-util.workspace = true
gtk4.workspace = true
gtk4-layer-shell.workspace = true
libc.workspace = true
kshell-niri.workspace = true
kshell-theme.workspace = true
